# Debian Bookworm deps image for Catapult builds
# This image installs system build dependencies and builds + installs the mongo-cxx driver.

FROM debian:bookworm

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install --no-install-recommends -y \
    curl \
    git \
    build-essential \
    cmake \
    pkg-config \
    ca-certificates \
    wget \
    libmongoc-1.0-0 \
    libmongoc-dev \
    libzstd-dev \
    librocksdb-dev \
    libczmq-dev \
    libsasl2-dev \
    libssl-dev \
    libboost-dev \
    libboost-atomic-dev \
    libboost-date-time-dev \
    libboost-regex-dev \
    libboost-system-dev \
    libboost-timer-dev \
    libboost-chrono-dev \
    libboost-log-dev \
    libboost-thread-dev \
    libboost-filesystem-dev \
    libboost-program-options-dev \
    libboost-stacktrace-dev \
    libboost-random-dev \
    libzmq3-dev \
    cppzmq-dev \
    pkgconf \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/local/src

# Build and install mongo-cxx (r3.6.7 to match existing Dockerfiles)
RUN curl -fsSL -O https://github.com/mongodb/mongo-cxx-driver/releases/download/r3.6.7/mongo-cxx-driver-r3.6.7.tar.gz \
  && tar -xzf mongo-cxx-driver-r3.6.7.tar.gz \
  && mkdir mongo-cxx-driver-r3.6.7/build && cd mongo-cxx-driver-r3.6.7/build \
  && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DBSONCXX_POLY_USE_BOOST=1 .. \
  && make -j$(nproc) && make install \
  && cd /usr/local/src && rm -rf mongo-cxx-driver-r3.6.7* \
  && ldconfig

LABEL maintainer="proximax-storage"
ENV PATH="/usr/local/bin:${PATH}"
